// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniversityParking.Infrastructure.Persistence;

#nullable disable

namespace UniversityParking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008214600_AddStudentRegistrationStatuses")]
    partial class AddStudentRegistrationStatuses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniversityParking.Domain.AcademicPeriods.AcademicPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_academic_periods_name");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("ux_academic_periods_single_active")
                        .HasFilter("status = 'ACTIVE'");

                    b.ToTable("academic_periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_academic_periods_dates", "starts_on < ends_on");

                            t.HasCheckConstraint("ck_academic_periods_status", "status IN ('PLANNED', 'ACTIVE', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_audit_logs_action");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("UniversityParking.Domain.Incidents.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("parking_lot_id");

                    b.Property<Guid?>("ParkingMovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("parking_movement_id");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_incidents_occurred_at");

                    b.HasIndex("ParkingLotId");

                    b.HasIndex("ParkingMovementId");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_incidents_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_incidents_type");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("incidents", null, t =>
                        {
                            t.HasCheckConstraint("ck_incidents_resolution", "(status = 'RESOLVED' AND resolution IS NOT NULL AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL) OR (status = 'OPEN' AND resolved_by IS NULL AND resolved_at IS NULL) OR status = 'CANCELLED'");

                            t.HasCheckConstraint("ck_incidents_status", "status IN ('OPEN', 'RESOLVED', 'CANCELLED')");

                            t.HasCheckConstraint("ck_incidents_type", "type IN ('DAMAGE', 'ACCIDENT', 'SECURITY', 'DOCUMENT', 'BEHAVIOR', 'OTHER')");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Incidents.IncidentAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("incident_attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_incident_attachments_size", "size_bytes > 0");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.News.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PublishedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_news_published_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_news_status");

                    b.ToTable("news", null, t =>
                        {
                            t.HasCheckConstraint("ck_news_state", "(status = 'DRAFT' AND published_at IS NULL AND archived_at IS NULL) OR (status = 'PUBLISHED' AND published_at IS NOT NULL AND archived_at IS NULL) OR (status = 'ARCHIVED' AND archived_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_news_status", "status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Parking.ParkingLot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("campus");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closing_time");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opening_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Campus")
                        .IsUnique()
                        .HasDatabaseName("ux_parking_lots_name_campus");

                    b.ToTable("parking_lots", null, t =>
                        {
                            t.HasCheckConstraint("ck_parking_lots_schedule", "opening_time < closing_time");

                            t.HasCheckConstraint("ck_parking_lots_status", "status IN ('ACTIVE', 'INACTIVE')");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Parking.ParkingMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_at");

                    b.Property<Guid>("CheckInGuardId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_in_guard_id");

                    b.Property<DateTimeOffset?>("CheckOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_at");

                    b.Property<Guid?>("CheckOutGuardId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_out_guard_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("parking_lot_id");

                    b.Property<Guid>("ParkingZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("parking_zone_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("CheckInAt")
                        .HasDatabaseName("ix_parking_movements_check_in");

                    b.HasIndex("CheckInGuardId");

                    b.HasIndex("CheckOutGuardId");

                    b.HasIndex("ParkingLotId");

                    b.HasIndex("ParkingZoneId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_parking_movements_status");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_parking_movements_open_user")
                        .HasFilter("status = 'OPEN'");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ux_parking_movements_open_vehicle")
                        .HasFilter("status = 'OPEN'");

                    b.HasIndex("UserId", "CheckInAt")
                        .HasDatabaseName("ix_parking_movements_user_check_in");

                    b.HasIndex("VehicleId", "CheckInAt")
                        .HasDatabaseName("ix_parking_movements_vehicle_check_in");

                    b.ToTable("parking_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_parking_movements_state", "(status = 'OPEN' AND check_out_at IS NULL AND check_out_guard_id IS NULL) OR (status = 'CLOSED' AND check_out_at IS NOT NULL AND check_out_guard_id IS NOT NULL AND check_out_at >= check_in_at)");

                            t.HasCheckConstraint("ck_parking_movements_status", "status IN ('OPEN', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Parking.ParkingZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("parking_lot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId", "VehicleType")
                        .IsUnique()
                        .HasDatabaseName("ux_parking_zones_lot_type");

                    b.ToTable("parking_zones", null, t =>
                        {
                            t.HasCheckConstraint("ck_parking_zones_status", "status IN ('ACTIVE', 'INACTIVE')");

                            t.HasCheckConstraint("ck_parking_zones_type", "vehicle_type IN ('CAR', 'MOTORCYCLE', 'BICYCLE')");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Universities.University", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("Code").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("code");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("name");
                    b.Property<bool>("IsActive").HasColumnType("boolean").HasColumnName("is_active");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id");
                    b.HasIndex("Code").IsUnique().HasDatabaseName("ux_universities_code");
                    b.ToTable("universities", t =>
                        {
                            t.HasCheckConstraint("ck_universities_code", "code <> '' AND code = upper(btrim(code))");
                            t.HasCheckConstraint("ck_universities_name", "btrim(name) <> ''");
                            t.HasCheckConstraint("ck_universities_dates", "updated_at >= created_at");
                        });
                    b.HasData(
                        new { Id = new Guid("a1100000-0000-4000-8000-000000000001"), Code = "ETITC", Name = "ETITC", IsActive = true,
                            CreatedAt = new DateTimeOffset(2026, 10, 8, 0, 0, 0, TimeSpan.Zero), UpdatedAt = new DateTimeOffset(2026, 10, 8, 0, 0, 0, TimeSpan.Zero) },
                        new { Id = new Guid("a1100000-0000-4000-8000-000000000002"), Code = "CMC", Name = "Colegio Mayor de Cundinamarca", IsActive = true,
                            CreatedAt = new DateTimeOffset(2026, 10, 8, 0, 0, 0, TimeSpan.Zero), UpdatedAt = new DateTimeOffset(2026, 10, 8, 0, 0, 0, TimeSpan.Zero) },
                        new { Id = new Guid("a1100000-0000-4000-8000-000000000003"), Code = "UPN", Name = "U. Pedagógica", IsActive = true,
                            CreatedAt = new DateTimeOffset(2026, 10, 8, 0, 0, 0, TimeSpan.Zero), UpdatedAt = new DateTimeOffset(2026, 10, 8, 0, 0, 0, TimeSpan.Zero) });
                });

            modelBuilder.Entity("UniversityParking.Domain.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_code");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("UniversityParking.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("card_code");

                    b.Property<string>("Career")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("career");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identification_number");

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("member_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UniversityId").HasColumnType("uuid").HasColumnName("university_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CardCode")
                        .IsUnique()
                        .HasDatabaseName("ux_users_card_code");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_users_identification_number");

                    b.HasIndex("UniversityId").HasDatabaseName("ix_users_university_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_member_type", "member_type IN ('STUDENT', 'TEACHER', 'STAFF')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('ACTIVE', 'PENDING', 'INACTIVE', 'REJECTED')");

                            t.HasCheckConstraint("ck_users_student_career", "member_type <> 'STUDENT' OR (career IS NOT NULL AND btrim(career) <> '')");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Users.UserCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("UniversityParking.Domain.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("UniversityParking.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FrameNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frame_number");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Plate")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("plate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FrameNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_frame_number")
                        .HasFilter("frame_number IS NOT NULL");

                    b.HasIndex("Plate")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_plate")
                        .HasFilter("plate IS NOT NULL");

                    b.ToTable("vehicles", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicles_identifier", "(type IN ('CAR', 'MOTORCYCLE') AND plate IS NOT NULL AND frame_number IS NULL) OR (type = 'BICYCLE' AND plate IS NULL AND frame_number IS NOT NULL)");

                            t.HasCheckConstraint("ck_vehicles_status", "status IN ('ACTIVE', 'INACTIVE')");

                            t.HasCheckConstraint("ck_vehicles_type", "type IN ('CAR', 'MOTORCYCLE', 'BICYCLE')");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Vehicles.VehicleDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_number");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("vehicle_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_documents_dates", "issued_on IS NULL OR expires_on IS NULL OR expires_on >= issued_on");

                            t.HasCheckConstraint("ck_vehicle_documents_size", "size_bytes > 0");

                            t.HasCheckConstraint("ck_vehicle_documents_type", "type IN ('VEHICLE_REGISTRATION', 'INSURANCE', 'OWNERSHIP_SUPPORT', 'OTHER')");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Vehicles.VehicleOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("TransferReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("transfer_reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicle_ownerships_current_vehicle")
                        .HasFilter("end_at IS NULL");

                    b.HasIndex("UserId", "EndAt")
                        .HasDatabaseName("ix_vehicle_ownerships_user_end_at");

                    b.ToTable("vehicle_ownerships", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_ownerships_dates", "end_at IS NULL OR end_at >= start_at");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Vehicles.VehiclePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("vehicle_photos", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_photos_size", "size_bytes > 0");

                            t.HasCheckConstraint("ck_vehicle_photos_type", "type = 'GENERAL'");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Vehicles.VehicleRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademicPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_period_id");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("AcademicPeriodId");

                    b.HasIndex("CancelledBy");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId", "AcademicPeriodId")
                        .HasDatabaseName("ix_vehicle_registrations_vehicle_period");

                    b.HasIndex("VehicleId", "UserId", "AcademicPeriodId")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicle_registrations_vehicle_user_period");

                    b.ToTable("vehicle_registrations", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_registrations_cancellation", "(status = 'ACTIVE' AND cancelled_at IS NULL AND cancelled_by IS NULL AND cancel_reason IS NULL) OR (status = 'CANCELLED' AND cancelled_at IS NOT NULL AND cancel_reason IS NOT NULL)");

                            t.HasCheckConstraint("ck_vehicle_registrations_status", "status IN ('ACTIVE', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("UniversityParking.Domain.Auditing.AuditLog", b =>
                {
                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("UniversityParking.Domain.Incidents.Incident", b =>
                {
                    b.HasOne("UniversityParking.Domain.Parking.ParkingLot", null)
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityParking.Domain.Parking.ParkingMovement", null)
                        .WithMany()
                        .HasForeignKey("ParkingMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversityParking.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("UniversityParking.Domain.Incidents.IncidentAttachment", b =>
                {
                    b.HasOne("UniversityParking.Domain.Incidents.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityParking.Domain.News.NewsItem", b =>
                {
                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityParking.Domain.Parking.ParkingMovement", b =>
                {
                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CheckInGuardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CheckOutGuardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversityParking.Domain.Parking.ParkingLot", null)
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityParking.Domain.Parking.ParkingZone", null)
                        .WithMany()
                        .HasForeignKey("ParkingZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityParking.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityParking.Domain.Parking.ParkingZone", b =>
                {
                    b.HasOne("UniversityParking.Domain.Parking.ParkingLot", null)
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityParking.Domain.Users.UserCredential", b =>
                {
                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("UniversityParking.Domain.Users.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityParking.Domain.Users.UserRole", b =>
                {
                    b.HasOne("UniversityParking.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityParking.Domain.Vehicles.VehicleDocument", b =>
                {
                    b.HasOne("UniversityParking.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityParking.Domain.Vehicles.VehicleOwnership", b =>
                {
                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityParking.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityParking.Domain.Vehicles.VehiclePhoto", b =>
                {
                    b.HasOne("UniversityParking.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityParking.Domain.Vehicles.VehicleRegistration", b =>
                {
                    b.HasOne("UniversityParking.Domain.AcademicPeriods.AcademicPeriod", null)
                        .WithMany()
                        .HasForeignKey("AcademicPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CancelledBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversityParking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityParking.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
            modelBuilder.Entity("UniversityParking.Domain.Users.User", b =>
                {
                    b.HasOne("UniversityParking.Domain.Universities.University", null)
                        .WithMany().HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
